name: Jekyll Build

on:
  push:
    branches:
      - main  # or your preferred branch
  workflow_dispatch:  # allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'  # Adjust to your Jekyll-supported Ruby version

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build Jekyll site
        run: bundle exec jekyll build

      - name: Upload _site artifact
        uses: actions/upload-artifact@v4
        with:
          name: jekyll-site
          path: _site

